version: 0.0
os: linux
files:
  - source: SampleApp_Linux/index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: SampleApp_Linux/scripts/install_dependencies
      timeout: 300
      runas: root
    - location: SampleApp_Linux/scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: SampleApp_Linux/scripts/stop_server
      timeout: 300
      runas: root

